# Generated by Django 3.2.18 on 2023-04-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inimene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=200)),
                ('raha', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='tehing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kogus', models.DecimalField(decimal_places=2, max_digits=200)),
                ('selgitus', models.CharField(default='Selgitus puudub.', max_length=10000)),
                ('saaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rakendus.inimene')),
            ],
        ),
    ]
