# Generated by Django 4.2 on 2023-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rakendus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tehing',
            name='andja',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tehing',
            name='saaja',
            field=models.CharField(max_length=200),
        ),
    ]
