# Generated by Django 4.1.7 on 2023-04-23 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Rakendus', '0003_tehing_aeg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehing',
            name='aeg',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tehingu toimumise aeg'),
        ),
    ]
