# Generated by Django 4.1.7 on 2023-04-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rakendus', '0004_alter_tehing_aeg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inimene',
        ),
    ]
