# Generated by Django 4.1.7 on 2023-04-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rakendus', '0005_delete_inimene'),
    ]

    operations = [
        migrations.CreateModel(
            name='inimene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=200)),
                ('raha', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
        ),
    ]
